<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>NoLeaves</AssemblyName>
    <Description>BepInEx plugin that removes forest leaves in Gorilla Tag</Description>
    <Version>1.1.4</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <GorillaTagDir>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag</GorillaTagDir>
    <GorillaTagPluginsDir>$(GorillaTagDir)\BepInEx\plugins</GorillaTagPluginsDir>
    <BepInExCoreDir>$(GorillaTagDir)\BepInEx\core</BepInExCoreDir>
    <GorillaTagManagedDir>$(GorillaTagDir)\Gorilla Tag_Data\Managed</GorillaTagManagedDir>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="GitHub\**\*.cs" />
    <None Include="GitHub\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCoreDir)\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GorillaTagManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="GT_CustomMapSupportRuntime">
      <HintPath>$(GorillaTagManagedDir)\GT_CustomMapSupportRuntime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCoreDir)\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>$(BepInExCoreDir)\MonoMod.Utils.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Photon3Unity3D">
      <HintPath>$(GorillaTagManagedDir)\Photon3Unity3D.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>$(GorillaTagManagedDir)\PhotonRealtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>$(GorillaTagManagedDir)\PhotonUnityNetworking.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PhotonVoice.API">
      <HintPath>$(GorillaTagManagedDir)\PhotonVoice.API.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PhotonVoice">
      <HintPath>$(GorillaTagManagedDir)\PhotonVoice.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PhotonVoice.PUN">
      <HintPath>$(GorillaTagManagedDir)\PhotonVoice.PUN.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>$(GorillaTagManagedDir)\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>$(GorillaTagManagedDir)\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GorillaTagManagedDir)\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.AnimationModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.AudioModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>


    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCoreDir)\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GorillaTagManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="GT_CustomMapSupportRuntime">
      <HintPath>$(GorillaTagManagedDir)\GT_CustomMapSupportRuntime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCoreDir)\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>$(BepInExCoreDir)\MonoMod.Utils.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Photon3Unity3D">
      <HintPath>$(GorillaTagManagedDir)\Photon3Unity3D.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>$(GorillaTagManagedDir)\PhotonRealtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>$(GorillaTagManagedDir)\PhotonUnityNetworking.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PhotonVoice.API">
      <HintPath>$(GorillaTagManagedDir)\PhotonVoice.API.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PhotonVoice">
      <HintPath>$(GorillaTagManagedDir)\PhotonVoice.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PhotonVoice.PUN">
      <HintPath>$(GorillaTagManagedDir)\PhotonVoice.PUN.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Core.Runtime">
      <HintPath>$(GorillaTagManagedDir)\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.RenderPipelines.Universal.Runtime">
      <HintPath>$(GorillaTagManagedDir)\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GorillaTagManagedDir)\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.AnimationModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.AudioModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>


    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>$(GorillaTagManagedDir)\UnityEngine.VideoModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Valve.Newtonsoft.Json">
      <HintPath>$(GorillaTagManagedDir)\Valve.Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(GorillaTagManagedDir)\Unity.InputSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyPluginToGorillaTag" AfterTargets="CopyFilesToOutputDirectory" Condition="Exists('$(GorillaTagPluginsDir)') and Exists('$(TargetDir)$(AssemblyName).dll')">
    <Message Text="Deploying $(AssemblyName).dll to $(GorillaTagPluginsDir)" Importance="high" />
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).dll" DestinationFolder="$(GorillaTagPluginsDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
